### ISSUE TITLE
Reverse named_scopes not only for just equal

### ISSUE THREAD

**Issue by nicolasblanco** [binarylogic/searchlogic#1]
It would be very cool to also have "reverse" named_scope for all conditions, not only equal.

For example :

<pre>
  User.username_not_blank
  User.username_not_empty
  User.username_does_not_end_with("bjohnson")
  User.username_does_not_begin_with("bjohnson")
</pre>

and so on...

I may try to help for this :).

Nicolas

**Comment by sheldonh** [comment]
Bigtime. I've run into this with LIKE, and got suspicious results (duplicated rows) when I tried it myself across a join.

**Comment by ghost** [comment]
This has been in searchlogic for a couple of weeks now, sorry for not noticing this. But you should be good to go.

**Comment by tomash** [comment]
this is a great feature, but any chance searchlogic will also get something like column_not_equals or even column_not_equals_any([1,2,3])?
