### ISSUE TITLE
on rails edge method not found

### ISSUE THREAD

**Issue by masterkain** [binarylogic/searchlogic#111]
I'm using Rails 2.3 (latest git), after an upgrade today searchlogic broke.

It should be noted that I'm using searchlogic 2.4.12 because of issue #99
Also this pastie contains comments on another issue with searchlogic. Searching for '..' will result in an exception.

NoMethodError: undefined method `title_like_before_type_cast' for #Class:0x92048e8
Full details and trace: http://pastie.org/1098763

**Comment by masterkain** [comment]
related: http://github.com/rails/rails/commit/fb0bd8c1092db51888ec4bb72af6c595e13c31fa

**Comment by icoretech** [comment]
This problem is still present with the latest searchlogic gem. Any word about this?
