### ISSUE TITLE
Where do I define searchlogics scoped procedures?

### ISSUE THREAD

**Issue by timfong888** [binarylogic/searchlogic#127]
I see the example:
[code]
User.scope_procedure :awesome, lambda { name_begins_with("Ben").name_ends_with("Johnson") }
[/code]

But where do I define this, can I put this in the User.rb?  This syntax is different from define named procedures, for example.

**Comment by ghost** [comment]
In the same exact place you defined named_scopes

**Comment by timfong888** [comment]
ah, gotcha, I figured it out -- it wasn't working because needed to hit reload! in the console....
