### ISSUE TITLE
Big and Ugly URL

### ISSUE THREAD

**Issue by RaduPoe** [binarylogic/searchlogic#132]
I have some long fields created by the fact that I am searching in related objects and my querystring becomes huge.

Is there a possibility to save the search params in a hidden field or in a session variable instead of merging them into querystring?

**Comment by ghost** [comment]
This is really unrelated to searchlogic. But you can submit a POST request instead of GET. Other than that, there really is nothing wrong with multiple parameters in your URL, if thats how your searching works. You could leverage something like sphinx and have them search based on a single query.
