### ISSUE TITLE
Rails3: undefined method `merge_joins' for class `Class' (NameError)

### ISSUE THREAD

**Issue by stuffmc** [binarylogic/searchlogic#138]
/.rvm/gems/ruby-1.8.7-p302@rails3/gems/activesupport-3.0.3/lib/active_support/core_ext/module/aliasing.rb:31:in `alias_method': undefined method`merge_joins' for class `Class' (NameError)

**Comment by fro** [comment]
Same problem here...

**Comment by danielavdh** [comment]
me too - solution?

**Comment by fro** [comment]
Yup, use meta_search instead ;-)

**Comment by danielavdh** [comment]
precisely what i have done :) thanks

**Comment by erskingardner** [comment]
I'm still seeing this problem with rails 3.1.beta1

**Comment by ghost** [comment]
Searchlogic is not rails 3 compatible yet. The internals of AR have changed considerably. The next version of SL will cover this.

**Comment by alirho** [comment]
same problem with rails 4.
