### ISSUE TITLE
2.4.31 breaks "in" queries when one of the param is nil/null 

### ISSUE THREAD

**Issue by nikhilgupte** [binarylogic/searchlogic#142]
In 2.4.30, Foo.field1_in('a', 'b', nil) generated a bunch of OR clauses which handled the NULL check
2.4.31 generates an IN clause like field1 IN ('a', 'b', NULL). This does not work in PostgreSQL.

**Comment by ghost** [comment]
This has been fixed, update to the latest version. Thanks.
