### ISSUE TITLE
order() doesn&rsquo;t order correctly from searchlogic > 2.1.5

### ISSUE THREAD

**Issue by ghost** [binarylogic/searchlogic#16]
Please find attached test app to demonstrate the strangely order/sorting behaviour with searchlogic > 2.1.5

[original LH ticket](http://binarylogic.lighthouseapp.com/projects/16601/tickets/110)

 This ticket has 1 attachment(s).

**Comment by ghost** [comment]
Can you please create a failing test for this. It would be much easier. I couldn't reproduce any problems with the app. Thank you.

**Comment by ZenCocoon** [comment]
The app give the expected results to me as well.
The only confusing part is that some of your items names start by a capital and not some others so can look failling at a first look while it give the expected result.
