### ISSUE TITLE
scope on a column beginning with the name of an association

### ISSUE THREAD

**Issue by etaque** [binarylogic/searchlogic#2]
Giving this models :
User has_many :classifieds
Classified

User model has the column "classifieds_count".

This search throws an error, because it seems to ignore User.classifieds_count column and to search on the associated Classified model :
User.classifieds_count_greater_than(5)

Emilien

**Comment by etaque** [comment]
also posted on lighthouse:
http://binarylogic.lighthouseapp.com/projects/16601/tickets/92-conflict-with-a-scope-on-a-column-beginning-with-the-name-of-an-association

**Comment by joost** [comment]
Has anyone got a quick fix for this? I would love to have it!!

**Comment by ghost** [comment]
This has been fixed, let me know if you have any other issues.

**Comment by xrx** [comment]
Thanks for fixing this, i had the exact same problem.
