### ISSUE TITLE
Simple OR conditions

### ISSUE THREAD

**Issue by ryanb** [binarylogic/searchlogic#20]
It would be nice if one could do a simple `OR` condition like this.

<pre>
Article.name_or_content_like("something")
</pre>

I imagine the method_missing call could do a check for "`_or_`" in the name, split by it, and add a condition for each resulting attribute.

**Comment by ghost** [comment]
Yeah, that's definitely doable. I'll throw something together for that.

**Comment by josespinal** [comment]
Thanks!

**Comment by ghost** [comment]
This has been added. It was actually pretty fun to code. Anyways, checkout the readme for some examples, or checkout the specs:

http://github.com/binarylogic/searchlogic/blob/24bc3715a2baf3a21ae95d0d7d7d8f2868503458/spec/named_scopes/or_conditions_spec.rb

Let me know if you have any issues.

**Comment by nickd** [comment]
This works for me in a simple case like 

```
Address.first_or_last_like("something")
```

but im having problems with associations:

```
#Customer => has_many addresses
Customer.address_first_or_address_last_like("something")
# => error: The condition 'address_first' is not a valid condition, we could not find any scopes that match this.
Customer.address_first_like_or_address_last_like("something")
# => error: The condition 'address_last_like' is not a valid condition, we could not find any scopes that match this
```

Also (im not sure why i was trying this) but this gave me a stack level too deep:

```
Customer.address_first_like_or_id_equals(0)
```
