### ISSUE TITLE
blank and not_blank conditions

### ISSUE THREAD

**Issue by brentd** [binarylogic/searchlogic#22]
Just as ActiveSupport adds the blank? and present? methods to Object to detect if something is either nil or a blank string/array/whatever, I thought it might be nice to provide the blank and not_blank conditions in searchlogic.

Example:

```
Person.first_name_blank
# => SELECT * FROM people WHERE first_name != '' OR first_name IS NULL
```

Just something we've found to be convenient for our app. Patch w/ specs can be found here:

http://gist.github.com/174043

**Comment by ledermann** [comment]
Commited to bedecfcfabf94dd482a366e1004e74e135d79975, but I think it's not correct:

not_blank should be

```
column != "" AND column IS NOT NULL
```

You see, AND instead of OR. Otherwise, the result set includes empty strings.

**Comment by ghost** [comment]
Cool, this has been added

**Comment by brentd** [comment]
You're quite right about that. I rewrote the spec for non_blank to be a little bit more clear. Here's the new patch:

http://gist.github.com/174204

Granted, I think that just saying column != '' will have the same results, since I believe NULL values won't even be considered in a string comparison. I left it as you suggested though for completeness' sake.

**Comment by ledermann** [comment]
Great, thanks!

**Comment by ledermann** [comment]
Hm, this issue show be re-opened until Ben has commited the patch...

**Comment by ghost** [comment]
Thanks, this has been fixed.
