### ISSUE TITLE
Critical Named Scope not created properly

### ISSUE THREAD

**Issue by tgnj** [binarylogic/searchlogic#26]
> > User.id_ne(10).login_not_like("root").count
> > => 2644
> > User.id_ne(10).login_not_like("root").count
> > => 2643

this produces

  SQL (1.7ms)   SELECT count(_) AS count_all FROM `users` WHERE (users.login LIKE '%root%') 
  SQL (3.9ms)   SELECT count(_) AS count_all FROM `users` WHERE ((users.login LIKE '%root%') AND (users.id != 10))

**Comment by ghost** [comment]
This is passing for me:

<pre>
it "should fix bug for issue 26" do
    count1 = User.id_ne(10).username_not_like("root").count
    count2 = User.id_ne(10).username_not_like("root").count
    count1.should == count2
  end
</pre>


Can you write a failing test?
