### ISSUE TITLE
Exception "undefined method `call' for nil:NilClass"

### ISSUE THREAD

**Issue by nicolasblanco** [binarylogic/searchlogic#27]
Hi,

I had a weird exception on my production server when using a Searchlogic named_scope, here is 
the code :

<pre>
def index
  @products = Product.available.ascend_by_position.all
  # ... 
end
</pre>

available is a regular named_scope and ascend_by_position is a Searchlogic named_scope on the position column.

The exception :

<pre>
Error Message:
--------------
NoMethodError: undefined method `call' for nil:NilClass

Where:
------
orders#index
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/named_scope.rb, line 97

Backtrace:
----------
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/named_scope.rb:97:in `ascend_by_position'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/named_scope.rb:181:in `send'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/named_scope.rb:181:in `method_missing'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/base.rb:2143:in `with_scope'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/named_scope.rb:113:in `__send__'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/named_scope.rb:113:in `with_scope'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/named_scope.rb:174:in `method_missing'
[RAILS_ROOT]/app/controllers/orders_controller.rb:4:in `index'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/base.rb:1331:in `send'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/base.rb:1331:in `perform_action_without_filters'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/filters.rb:617:in `call_filters'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
[GEM_ROOT]/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:17:in `ms'
[GEM_ROOT]/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:10:in `realtime'
[GEM_ROOT]/gems/activesupport-2.3.4/lib/active_support/core_ext/benchmark.rb:17:in `ms'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/flash.rb:146:in `perform_action'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/base.rb:532:in `send'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/base.rb:532:in `process_without_filters'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/filters.rb:606:in `sass_old_process'
[GEM_ROOT]/gems/haml-2.2.3/rails/../lib/sass/plugin/rails.rb:19:in `process'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/base.rb:391:in `process'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/base.rb:386:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/routing/route_set.rb:437:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:87:in `dispatch'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:121:in `_call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/vendor/rack-1.0.0-git/lib/rack/head.rb:9:in `call'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/vendor/rack-1.0.0-git/lib/rack/head.rb:9:in `call'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/vendor/rack-1.0.0-git/lib/rack/methodoverride.rb:24:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/params_parser.rb:15:in `call'
[GEM_ROOT]/gems/rails-2.3.4/lib/rails/rack/metal.rb:47:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/session/abstract_store.rb:122:in `call'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/query_cache.rb:29:in `call'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/query_cache.rb:9:in `cache'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/query_cache.rb:28:in `call'
[GEM_ROOT]/gems/activerecord-2.3.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/failsafe.rb:26:in `call'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/vendor/rack-1.0.0-git/lib/rack/lock.rb:11:in `call'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/vendor/rack-1.0.0-git/lib/rack/lock.rb:11:in `synchronize'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/vendor/rack-1.0.0-git/lib/rack/lock.rb:11:in `call'
[GEM_ROOT]/gems/actionpack-2.3.4/lib/action_controller/dispatcher.rb:106:in `call'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/rack/request_handler.rb:95:in `process_request'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/railz/application_spawner.rb:378:in `start_request_handler'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/railz/application_spawner.rb:336:in `handle_spawn_application'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/utils.rb:183:in `safe_fork'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/railz/application_spawner.rb:334:in `handle_spawn_application'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server.rb:163:in `start'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/railz/application_spawner.rb:213:in `start'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/opt/ruby-enterprise/lib/ruby/gems/1.8/gems/passenger-2.2.5/bin/passenger-spawn-server:61
</pre>

The weird thing is that I only had this exception on my production server, never had it on my development box.
I tried with and without the .all at the end of line without success. I had to remove the searchlogic named_scope and replace it by a regular named_scope to get rid of this exception.

**Comment by ghost** [comment]
I'm really not sure, its hard for me to determine the problem from this. Is it just this named scope?

**Comment by nicolasblanco** [comment]
Hi Ben, I had this problem again, it seems to be only on this named_scope, strange.
I'll try to investigate more.

**Comment by austinginder** [comment]
I had similar issues between development and production. It may not be related but I fix my problem by downgraded from version 2.3.6 to 2.3.5 on my production server, restarted apache and its working.

**Comment by austinginder** [comment]
well scratch that, I still get the problem, its weird it only happens after the rails app has been running for awhile. Every time I get the problem I can restart my app and it fixes it. Its really annoying as the problem comes back after a day.

**Comment by nicolasblanco** [comment]
well. maybe we should also check which version of ruby we are using. in my case : REE 1.8.6. I'll try updating to REE 1.8.7 in some days...

**Comment by nicolasblanco** [comment]
austinginder, do you also get this exception when mixing searchlogic named_scope with a model named_scope and which are the name of your named_scopes ?

**Comment by austinginder** [comment]
My development server is running 
ruby 1.8.7 (2008-08-11 patchlevel 72) [universal-darwin10.0] 

while my production (the one with the issues) is running 
ruby 1.8.7 (2009-06-12 patchlevel 174) [x86_64-linux]

I am using the following search logic named scope:
@assets = TempAsset.processing_eq(true)
I've also tried changing it to:
@assets = TempAsset.processing_equals(true)
Both lines give the mysterious NoMethodError.

TempAsset looks like this:
TempAsset(id: integer, title: string, artist: string, length_in_seconds: integer, media_file_name: string, media_content_type: string, media_file_size: integer, created_at: datetime, updated_at: datetime, processing: boolean)

**Comment by stephankaag** [comment]
This look related and happens only with cache_classes turned on.:

<pre>
class House < ActiveRecord::Base
end

class Admin::House < House
end
  
>> House.order
>> Admin::House.order  

NoMethodError: undefined method `call' for nil:NilClass
</pre>

**Comment by mrcsparker** [comment]
Same problem here, running ruby 1.9 with rails 2.3.5

**Comment by omarvelous** [comment]
You guys try the plugin?

**Comment by stephankaag** [comment]
I indeed do use the plugin

**Comment by stephankaag** [comment]
I did some more investigation. This problem is a Rails bug and not searchlogic related. 

I will open a Rails ticket tomorrow.

**Comment by ghost** [comment]
thanks

**Comment by espen** [comment]
I am using STI with my model and believe that affects this. This bug occurs when going from a search on the main model which includes restults from the main model and the child model, to a search for the child model. Same code works normally otherwise.

Where can I find the rails ticket for this bug?

**Comment by nikhilgupte** [comment]
I think, I narrowed this issue down and notice it on only those STI classes that also use:
has_many_polymorphs

Does that help?

**Comment by espen** [comment]
I do not use has_many_polymorphs

**Comment by stephankaag** [comment]
Rails ticket: https://rails.lighthouseapp.com/projects/8994/tickets/3766-on-the-fly-created-named-scope-raises-undefined-method-call-when-called-from-subclass-with-cache_classes-true
