### ISSUE TITLE
ascend and descend

### ISSUE THREAD

**Issue by punund** [binarylogic/searchlogic#5]
> s = Person.search
> s.ascend_by_name true
> s.all
> |  Andy
> |  Bob
> |  Charlie
>   . . . . .
> s.descend_by_name true
> s.all
> |  Andy
> |  Bob
> |  Charlie
>   . . . . .
> s.ascend_by_name false
> s.all
> |  Zita
> |  Yvonne
> |  Xaviere
>   . . . . .

**Comment by otaviofcs** [comment]
why you need to use true or false? Just use ascend_by_name or descend_by_name and you will be fine.

**Comment by ghost** [comment]
Im not sure what the question is.
