### ISSUE TITLE
Example for combine scopes with ‘OR’ is incorrect

### ISSUE THREAD

**Issue by vandrijevik** [binarylogic/searchlogic#53]
The second example in the Readme under the "Combine scopes with ‘OR’" section reads:

```
User.id_or_age_lt_or_username_or_first_name_begins_with(10)
=> "id < 10 OR age < 10 OR username LIKE 'ben%' OR first_name like'ben%'"
```

however, running `User.id_or_age_lt_or_username_or_first_name_begins_with(10)` results in the SQL:

```
"id < 10 OR age < 10 OR username LIKE '10%' OR first_name LIKE '10%'"
```

being run. Trying something like:

```
User.id_or_age_lt_or_username_or_first_name_begins_with(10, "ben")
```

raises a ActiveRecord::PreparedStatementInvalid, so there is no way to get the users whose id or age is less than 10 or username or first name begins with "ben".

It seems that the only scopes this will work for are ones that take the same number of arguments, and operate on the same type of field (since username like '10%' makes little sense).

**Comment by kerinin** [comment]
I would _love_ to have this ability.  I can see two ways to implement the API, either as shown in the example
    User.id_equal_or_name_equals(4,'ben')
or by making it possible to switch from 'AND' to 'OR' when chaining by appending 'or_':
    User.id_equals(4).or_name_equals('ben')
I would prefer the latter approach, as it isn't ambiguous in cases where multiple arguments are being matched against:
    User.id_equals_or_age_equals(16,17)
could be interpreted as id=16 || age=17 or as id=[16||17] || age=[16||17]

**Comment by tomash** [comment]
I would prefer the latter aswell, it'll be also kind of searchlogic1-like. any news on that issue?

**Comment by ghazel** [comment]
Doesn't the later have ambiguous cases? For example:

```
User.email_equals('foo@foo.com').id_equals(4).or_name_equals('ben')
```

Does that mean `(email = "foo@foo.com" and id = 4) or name = 'ben'` or `email = "foo@foo.com" and (id = 4 or name = 'ben')`?

Whichever you pick, how would you change it to mean the other one? ;)

**Comment by kerinin** [comment]
I would interpret this as the latter, as you could have used the following syntax to explicitly denote the former: `User.email_equals_and_id_equals('foo@foo.com',4).or_name_equals('ben')`
The point being that 'and' conditions can be combined in a single function call, then 'or' sets can be grouped by '.'  

There's no clean way to do something like A || ( (B && C) || D ) though...
