### ISSUE TITLE
order Helper doesn't honor existing search params

### ISSUE THREAD

**Issue by kmarsh** [binarylogic/searchlogic#6]
Changing the end of order() to something like the following will work:

<pre>new_params = params[options[:params_scope]].merge({:order => new_scope})
link_to options[:as], url_for(options[:params_scope] => new_params), html_options</pre>

It worked for my simple app, not sure if its a comprehensive solution, though.

**Comment by otaviofcs** [comment]
it's already fixed for 2.0.2. See http://github.com/binarylogic/searchlogic/commit/c2c7c9374deeb9cb6ccaa072d795a4f1985df00d

**Comment by ghost** [comment]
Thanks.
