### ISSUE TITLE
INNER JOIN problems

### ISSUE THREAD

**Issue by pkondzior** [binarylogic/searchlogic#61]
After Searchlogic swiched from LEFT OUTER JOINS to INNER JOINS it is useless when you want to search for field that are null or blank in joined associations this: Example:
Ticket.

Ticket.resolver_first_name_blank will generate this query

SELECT `tickets`.\* FROM `tickets` INNER JOIN `users` ON `users`.id = `tickets`.resolver_id WHERE (users.first_name = '' OR users.first_name IS NULL)

So if i have 1 milion of tickets without resolver, it will return 0 Tickets

The same problem is when you want to order by first_name let's say you have this query
Ticket.order("ascend_by_request_last_name") -> 
SELECT `tickets`.\* FROM `tickets` INNER JOIN `users` ON `users`.id = `tickets`.resolver_id ORDER BY users.last_name ASC LIMIT 0, 30;

This will only return ordered list of Tickets with resolver, all tickets without resolver will be lost.

So switching from LEFT OUTER JOIN to INNER JOIN is not a solution, anyone have ideas how i could resolve this issue ?

**Comment by pkondzior** [comment]
I see that in ActiveRecord 2.0 this is issue for whole Eager Loading, now ActiveRecord is using only INNER JOIN :(

**Comment by ghost** [comment]
Its a contextual problem, there is no right answer. I think inner joins is the right default choice. If you need left outer you need to create your own named scope, or if you find yourself doing this a lot, build a cool little piece of code that lets you modify scopes. Like optional_*

**Comment by laurynas** [comment]
binarylogic, thanks for a tip! After some experimenting I worked out easy solution to this problem adding named_scopes:

```
class Item < ActiveRecord::Base

  named_scope :ascend_by_optional_category_title, 
                    :joins => "LEFT JOIN categories AS optional_categories ON optional_categories.id=items.category_id",
                    :order => "optional_categories.title"

  named_scope :descend_by_optional_category_title, 
                    :joins => "LEFT JOIN categories AS optional_categories ON optional_categories.id=items.category_id",
                    :order => "optional_categories.title DESC"

end
```

Then you can do:

```
Item.search( :order => :ascend_by_optional_category_title )
```

https://gist.github.com/716490
