### ISSUE TITLE
you can't use default_scope for ordering a model if you want searchlogic to order the  model  by the same column as your default_scope does

### ISSUE THREAD

**Issue by arndttouby** [binarylogic/searchlogic#7]

**Comment by kalasjocke** [comment]
Just add the table name to the default scopes order, its kind of uggly but it works.

  default_scope :order => "companies.name" 

for example.

**Comment by ghost** [comment]
Yeah, kalas has it right. Thanks.

**Comment by vsalbaba** [comment]
no, it does not.

**Comment by nikhilgupte** [comment]
Adding the table name to the default_scope does _not_ work. Why is this ticket closed?
