### ISSUE TITLE
Searchlogic search() may return duplicate rows in some cases

### ISSUE THREAD

**Issue by 6yf** [binarylogic/searchlogic#76]
search() may return duplicate rows in some special cases, e.g. search Post by tags_name_like("xx") and a row happens to have two tags which contains "xx", then this row was duplicate twice in the result. This is just for testing when working with acts_as_taggable_on gem.
Anyway I suggest that search() should make sure to return unique rows.
Thanks for your great gem!

**Comment by mkwiatkowski** [comment]
This is a duplicate of issue #35.

**Comment by 6yf** [comment]
Thanks infrared for your comment and workaround. Can this bug be fixed?

**Comment by anexiole** [comment]
hello, there,
 Any progress on this? :)

thank you :)

**Comment by dlupu** [comment]
Same problem here, Can this bug be fixed?
